ln -f -s ~/pnaimoli-dotfiles/.Rprofile ~/
ln -f -s ~/pnaimoli-dotfiles/.bash_profile ~/
ln -f -s ~/pnaimoli-dotfiles/.inputrc ~/
ln -f -s ~/pnaimoli-dotfiles/.lesskey ~/
ln -f -s ~/pnaimoli-dotfiles/.lesskey-in ~/
ln -f -s ~/pnaimoli-dotfiles/.synergy.conf ~/
ln -f -s ~/pnaimoli-dotfiles/.vimrc ~/
ln -f -s ~/pnaimoli-dotfiles/.gvimrc ~/
ln -f -s ~/pnaimoli-dotfiles/.vim ~/
